/* tb_gcr_read.v — unit testbench for the IWM (GCR) read path: 400K/800K.
 *
 * WHY THIS EXISTS (2026-08-05): mounting a raw 800K GCR image on hardware
 * gives "This disk is unreadable", and the driver posts -69 badCksmErr =
 * "addr mark checksum didn't check". The GCR ADDRESS field is generated by
 * floppy_track_encoder.v from track/sector/side/format with a checksum taken
 * over exactly those values, so the field is SELF-CONSISTENT by construction
 * — no image data is involved. A self-consistent field can therefore only
 * fail its checksum if the byte STREAM is damaged between the encoder and the
 * CPU. That is the IWM delivery path (floppy.v's byte-cell timer +
 * newByteReady, and swim.v's readDataLatch / readLatchClearTimer /
 * readDataArmDelay), which had no test coverage at all.
 *
 * WHAT IT DOES: drives the IWM soft switches the way the ROM does (enable
 * drive, select internal, park the phases on RDDATA0, q6=q7=0), then polls
 * the data register and captures every byte whose MSB is set — exactly the
 * ROM's "valid read" criterion. Prints the captured stream as hex for
 * offline decoding by scripts/gcr_census.py.
 *
 * THE EXPERIMENT: +pollgap=N inserts N extra 32 MHz clocks between polls, so
 * the same stream can be read at different CPU rates.
 *   pollgap small  = an unrealistically fast reader. Corruption here means
 *                    the encoder/delivery is broken on its own.
 *   pollgap ~40    = ~1.25 us per access, the LC's real E-paced VPA rate.
 * A stream that is clean fast and dirty slow is a delivery/latch timing bug,
 * not an encoder bug.
 *
 * Build + run (Verilator 5.x, from verilator/):
 *   verilator --binary -j 0 -Wno-fatal --timescale 1ns/1ps +define+SIMULATION \
 *     -I../rtl --Mdir /tmp/obj_gcr --top-module tb_gcr_read tb_gcr_read.v \
 *     ../rtl/swim.v ../rtl/floppy.v ../rtl/mfm_track_encoder.v \
 *     ../rtl/floppy_track_encoder.v
 *   /tmp/obj_gcr/Vtb_gcr_read +pollgap=40 > gcr_stream.txt
 *   python ../scripts/gcr_census.py gcr_stream.txt
 */

`timescale 1ns/1ps

module tb_gcr_read;

	reg clk = 0;
	always #15.625 clk = ~clk;          // 32 MHz

	reg [1:0] phase = 0;
	always @(posedge clk) phase <= phase + 1'b1;
	wire cep = (phase == 2'd0);
	wire cen = (phase == 2'd2);

	reg _reset = 0;

	// ---- CPU-side SWIM bus
	reg        selectSWIM = 0;
	reg        _cpuRW = 1;
	reg        _cpuUDS = 1;
	reg [15:0] dataIn = 0;
	reg [3:0]  cpuAddrRegHi = 0;
	reg        SEL = 0;          // VIA PA5 / HDSEL: 0 => RDDATA0 = side 0
	reg        driveSel = 1;     // internal drive select (IWM _enable term)
	wire [15:0] dataOut;

	// ---- disk image model. The ADDRESS fields under test are generated from
	// geometry, not from image content, so the payload only needs to be
	// non-degenerate. Track 0 both sides = 12 sectors * 512 * 2 = 12288 B.
	localparam IMG_BYTES = 16384;
	reg [7:0] img [0:IMG_BYTES-1];

	wire [21:0] dskReadAddrInt, dskReadAddrExt;
	reg         dskReadAckInt = 0;
	wire        dskReadAckExt = 1'b0;
	wire [7:0]  dskReadData = (dskReadAddrInt < IMG_BYTES) ? img[dskReadAddrInt] : 8'hE5;

	// Periodic fetch ack, mimicking addrController's extra bus slot (~2 us).
	integer ack_div = 0;
	always @(posedge clk) begin
		if (cen) begin
			ack_div <= ack_div + 1;
			if (ack_div >= 8) begin
				ack_div <= 0;
				dskReadAckInt <= 1'b1;
			end else
				dskReadAckInt <= 1'b0;
		end
	end

	swim dut (
		.clk(clk), .cep(cep), .cen(cen),
		._reset(_reset),
		.selectSWIM(selectSWIM),
		._cpuRW(_cpuRW),
		._cpuUDS(_cpuUDS),
		.dataIn(dataIn),
		.cpuAddrRegHi(cpuAddrRegHi),
		.SEL(SEL),
		.driveSel(driveSel),
		.dataOut(dataOut),
		.insertDisk(2'b01),      // internal drive: disk in
		.diskEject(),
		.diskSides(2'b01),       // double-sided (800K)
		.diskMFM(2'b00),         // GCR disk -> IWM path
		.diskHD(2'b00),
		.diskMotor(), .diskAct(),
		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt),
		.dskReadData(dskReadData),
		.dbg_ism_flpe(),
		.dbg_flp_byte_cnt(), .dbg_flp_miss_cnt(), .dbg_flp_disk_data(),
		.dbg_flp_track(), .dbg_flp_side(), .dbg_flp_step_cnt(),
		.dbg_iwm_latch(), .dbg_flp_byte_stb(), .dbg_flp_raw(),
		.dbg_ism_state(),
		.dbg_flp_strb_cnt(), .dbg_flp_strb_en_cnt(), .dbg_flp_strb_last(),
		.dbg_flp_rej_step(), .dbg_flp_status(), .dbg_flp_gcr_addr(),
		.dbg_ism_verdict(), .dbg_ism_unrlatch(),
		.dbg_ism_scan(), .dbg_mfm_stall()
	);

	// ---- CPU access tasks. `pollgap` extra clocks model the real E-paced
	// VPA access rate (the SWIM sits in VPA space on the LC).
	integer pollgap = 0;

	task swim_wr(input [3:0] a, input [7:0] d);
	begin
		@(posedge clk);
		cpuAddrRegHi <= a; dataIn <= {8'h00, d}; _cpuRW <= 1'b0;
		selectSWIM <= 1'b1; _cpuUDS <= 1'b0;
		repeat (10) @(posedge clk);
		selectSWIM <= 1'b0; _cpuUDS <= 1'b1; _cpuRW <= 1'b1;
		repeat (10) @(posedge clk);
	end
	endtask

	task swim_rd(input [3:0] a, output [7:0] d);
	begin
		@(posedge clk);
		cpuAddrRegHi <= a; _cpuRW <= 1'b1;
		selectSWIM <= 1'b1; _cpuUDS <= 1'b0;
		repeat (10) @(posedge clk);
		d = dataOut[15:8];
		selectSWIM <= 1'b0; _cpuUDS <= 1'b1;
		repeat (10) @(posedge clk);
		if (pollgap > 0) repeat (pollgap) @(posedge clk);
	end
	endtask

	localparam NCAP = 6000;
	reg [7:0] cap [0:NCAP-1];
	integer   ncap = 0;

	reg [7:0] v;
	integer   i, guard;

	initial begin
		for (i = 0; i < IMG_BYTES; i = i + 1)
			img[i] = i[7:0] ^ 8'h5A;     // non-degenerate payload

		if (!$value$plusargs("pollgap=%d", pollgap)) pollgap = 0;

		_reset = 0;
		repeat (40) @(posedge clk);
		_reset = 1;
		repeat (40) @(posedge clk);

		// ---- IWM setup, exactly the soft-switch order the ROM uses ----
		swim_wr(4'd10, 8'h00);   // select INTERNAL drive (ext select off)
		swim_wr(4'd9,  8'h00);   // disk enable ON  (motor)
		swim_wr(4'd14, 8'h00);   // q7 = 0
		swim_wr(4'd12, 8'h00);   // q6 = 0  -> read data register
		// park the phases on RDDATA0 = {ca2,ca1,ca0,SEL} = 4'b1000
		swim_wr(4'd5,  8'h00);   // ca2 = 1
		swim_wr(4'd2,  8'h00);   // ca1 = 0
		swim_wr(4'd0,  8'h00);   // ca0 = 0
		SEL = 1'b0;              // side 0

		// the post-enable squelch in swim.v is ~126 us; wait it out
		repeat (200000) @(posedge clk);

		// ---- poll the data register; MSB set = a valid byte (ROM's rule) ----
		guard = 0;
		while (ncap < NCAP && guard < 40000000) begin
			swim_rd(4'd12, v);
			if (v[7]) begin
				cap[ncap] = v;
				ncap = ncap + 1;
			end
			guard = guard + 1;
		end

		$display("# tb_gcr_read pollgap=%0d captured=%0d", pollgap, ncap);
		for (i = 0; i < ncap; i = i + 1)
			$write("%02x%s", cap[i], ((i % 16) == 15) ? "\n" : " ");
		$write("\n");
		$finish;
	end

endmodule
